### ISSUE TITLE
PIPITS PROCESS Error: none zero returncode: biom convert

### ISSUE THREAD

**Issue by Sandra-ctrl** [hsgweon/pipits#45] opened 2021-02-16 18:16 UTC
Hi
I recently used the PIPITS to analyze my sequencing data in Dec and it was a success
but last week i tried to analyze another set of data and received this error code during the PIPITS Process
i looked through the previous issues and tried the options of updating scipy but still had the same error response
Do you know if there is a recent software update that may be interfering with smooth analysis
Thanks

Sandra

![pipits process error](https://user-images.githubusercontent.com/60274806/108104119-e2d56180-7058-11eb-8ffb-013fbaa53ec7.jpg)

**Comment by hsgweon** [comment] 2021-02-24 10:11
@Sandra-ctrl 
Sorry for the delayed response. I just have not had time to look at this but I'm on it now. 

I haven't been able to reproduce the result you have. 

Can you let me know what you get when you run the problematic line manually? So the command should be something like:

`biom convert -i /home/sandra/Fastq2/out_process2/intermediate/otu_table_prelim.txt -o /home/sandra/Fastq2/out_process2/intermediate/otu_table_prelim.biom --table-type="OTU table" --to-json`

**Comment by Sandra-ctrl** [comment] 2021-02-24 17:36
hi Soon,

Thanks for your reply

I appreciate it

Please find attached the error code when running PIPITS_PROCESS

I had used the PIPITS program in December and it was successful only to use it for a second batch of sequencing results this month and receive the error, Does it mean an update is required somewhere?

I tried using the test data on the PIPITS website and it did give an error (please find attached)

Thanks for your guidance on this issue


Sandra Nnadi

PhD Student

Plant Biology

Jeffords hall

________________________________

**Comment by hsgweon** [comment] 2021-02-24 19:14
Hi Sandra, you responded by email which is fine but the attachment can't be sent that way. Perhaps email me directly at h.s.gweon (at) reading.ac.uk ?

PIPITS hasn't been updated for over a year (I will update when a new UNITE database version is available) so it is possible that you have installed another tool(s) that uses a different version of biom package. But let's see if we can sort it out. So do send me the output, and also let me know what you get if you type:

`conda activate pipits_env` (only if you haven't done this already)
`biom --version`

**Comment by hsgweon** [comment] 2021-02-26 09:19
Closing the issue. It turns out that @Sandra-ctrl wasn't using the conda environment but wanted to run at base environment so installed biom-format manually to the system.

**Closed as completed by hsgweon** 2021-02-26 09:19 UTC
